# Generated by Django 5.2.1 on 2025-05-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='joined',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Joined'),
        ),
    ]
