# Generated by Django 5.2.1 on 2025-05-27 15:12

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Must be a jpg, jpeg, jfif, or png no larger than 200 x 200px.', null=True, upload_to='avatars/', validators=[users.models.validate_avatar]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='joined',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Joined'),
        ),
    ]
