# Generated by Django 5.2.1 on 2025-05-31 15:24

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_birthdate_customuser_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Must be a jpg, jpeg, jfif, or png no larger than 200 x 200px.', null=True, upload_to='avatars/', validators=[users.models.validate_avatar]),
        ),
    ]
