# Generated by Django 5.2.1 on 2025-05-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(help_text='(Please, enter a valid email address.)', max_length=250),
        ),
        migrations.AlterField(
            model_name='review',
            name='username',
            field=models.TextField(blank=True, help_text='(Optional)', max_length=100, null=True),
        ),
    ]
