# Generated by Django 5.2.1 on 2025-06-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_email_alter_review_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
