# Generated by Django 5.2.1 on 2025-05-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('game', models.TextField(choices=[('ANAGRAM_GAME', 'Anagram Hunt'), ('MATH_GAME', 'Math Facts')], default='ANAGRAM_GAME')),
                ('score', models.IntegerField()),
                ('game_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
