# Generated by Django 5.2.1 on 2025-05-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameFinalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('game_name', models.TextField(choices=[('ANAGRAM_GAME', 'Anagram Hunt'), ('MATH_GAME', 'Math Facts')], default='ANAGRAM_GAME')),
                ('final_score', models.IntegerField()),
                ('game_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GameScore',
        ),
    ]
