# Generated by Django 5.2.1 on 2025-05-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gamefinalscore_delete_gamescore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamefinalscore',
            old_name='game_datetime',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='gamefinalscore',
            old_name='final_score',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='gamefinalscore',
            old_name='username',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='gamefinalscore',
            name='game_name',
        ),
        migrations.AddField(
            model_name='gamefinalscore',
            name='game',
            field=models.TextField(choices=[('ANAGRAM', 'Anagram Hunt'), ('MATH', 'Math Facts')], default='MATH'),
        ),
    ]
