# Generated by Django 5.2.1 on 2025-05-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalscore',
            name='game_name',
            field=models.CharField(default='math_facts', editable=False, max_length=25),
            preserve_default=False,
        ),
    ]
