# Generated by Django 5.2.1 on 2025-05-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_rename_game_datetime_gamefinalscore_created_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameFinalScore',
            new_name='GameScore',
        ),
    ]
