# Generated by Django 5.2.1 on 2025-05-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_finalscore_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalscore',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
